title = "NBA Fantasy"
baseURL = "https://javiidoce.github.io/NbaFantasy/"
languageCode = "es"
theme = "gohugo-theme-ananke"
resourceDir = "../resources"


DefaultContentLanguage = "es"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = ""
  author = "Javier Melendo"
  creation_date= "2023"
  site_logo = "https://javiidoce.github.io/NbaFantasy/images/nba-logo.png"
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-purple"
  recent_posts_number = 3
  custom_css = ["custom.css","special.css"]

[[params.ananke_socials]]
  name = "twitter"
  url = "https://twitter.com/javiidoce"
